### PR TITLE
Ensure Token definition (XML) files are updated from the server

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Patch to ensure token definition files are periodically checked for updates on the repo server.

### CODE REVIEW

**Comment by hboon** [comment]
There's this in the [README](https://github.com/alpha-wallet/contracts/blob/master/README.md):

> When a user accesses a contract through its Ethereum address, the user's agent (mobile client) downloads or updates the XML files from this repo.
> 
> “access” happens when:
> 
> * the app discovers that the user has (or had) tokens under a Contract;
> * the user actively seek to use a Contract (scan its QR code or copying its address from the Internet);
> * the user gets sent Universal Link which refers to a Contract or its assets
> * the app launches

**Comment by colourful-land** [comment]
If you overlooked this part:
> Include the IF-Modified-Since header HTTP header with the local XML's last modified date in the GET request. If the XML on the server has not been modified, a 304 will be returned with an empty body.

Then you must have overlooked this part too:
> Be careful with timezone! Put a bit of thinking cases like this: the user moves from timezone A to timezone B and missing a latest update for up to 24 hours.

**Comment by JamesSmartCell** [comment]
Code is tested against files on FTP and the lastmodified header is honoured in those that support it. It should start working when the server fills the header in correctly. Would be preferable to use a hash system (which I believe is one of the RFC standards) but file time will be an improvement over what is there now.

**Comment by JamesSmartCell** [comment]
> Can you use a method not using the hourly timer? That look like the source of some evil.

See issue

**Comment by JamesSmartCell** [comment]
Ready for merge - please revisit

**Comment by JamesSmartCell** [comment]
Good idea.

**Comment by JamesSmartCell** [comment]
OK implemented @hboon suggestion. If all good then I'll upload a release candidate for testing & release for China trip.

**Comment by hboon** [comment]
Oh. Probably not in the scope of the PR, but I presume this is already handled already:

> When a user accesses a contract through its Ethereum address, the user's agent (mobile client) downloads or updates the XML files from this repo.
> 
> “access” happens when:
> 
> * the app discovers that the user has (or had) tokens under a Contract;
> * the user actively seek to use a Contract (scan its QR code or copying its address from the Internet);
> * the user gets sent Universal Link which refers to a Contract or its assets
> * the app launches

**Comment by JamesSmartCell** [comment]
Yep those events trigger search for XML definition from Repo server.

**Pull request merged**
